### ISSUE TITLE
Like it – wanna use it – need one thing

### ISSUE THREAD

**Issue by SundialServices** [Seretos/MysqliToPdoBundle#2]
I specifically need the ability to "seek()" a statement to an arbitrary record-number, not just to "rewind()."

A very easy addition to what you've now got.

_(Uhh, don't ask why.)_  **;-)**

**Comment by Seretos** [comment]
hm... it is easy in mysqli. but not in pdo.
i have written this bundle to switch between a mysqli and a pdo connection. (as one step in a project refactoring process).
i think it is a better way to limit the query to the correct result set.

Warning: I work currently on some changes on this bundle. If you use this repository, it is better, to create a fork from my repository.
